title: Servicii si Instalatii Electrice Complete (instalare si mentenanta)
email: alexamarius@yahoo.com
description: Electrician autorizat ANRE. Execuție instalații electrice de la zero, modernizare tablouri electrice și mentenanță în Iași și împrejurimi.
remote_theme: pages-themes/cayman@v0.2.0 # O temă profesională și curată
url: "https://www.alexavolt.ro"
baseurl: ""

plugins:
  - jekyll-remote-theme

google_analytics: G-GGBL0JG2KZ
