title: Panouri Electrice si Sisteme Fotovoltaice
email: contact@domeniultau.ro
description: Instalator autorizat ANRE. Soluții electrice si fotovoltaice complete.
baseurl: "" # lasă gol pentru domeniul principal
url: "https://alexa-eletric.github.io"

# Setări temă (Minima este tema default, sigură și rapidă)
plugins:
  - jekyll-feed
  - jekyll-remote-theme